source 'https://rubygems.org/'

group :development do
  gem 'rspec', '~> 3.5'
end

group :production do
  gem 'rugged', git: 'https://github.com/libgit2/rugged.git', tag: 'v0.19.0', submodules: true
end
