directories %w(lib spec .).select { |d|
  Dir.exists?(d) ? d : UI.warning("Directory #{d} does not exist")
}

guard :rspec, cmd: "bundle exec rspec" do
  watch(%r{lib/.+\.rb}) { 'spec/' }
  watch(%r{spec/.+\.rb})
end
